- name: manage aks
  hosts: localhost
  connection: local
  vars:
    resource_group: jieshe-collection-test
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
